CREATE TABLE cities (id INT PRIMARY KEY,name VARCHAR(100) NOT NULL);

INSERT INTO cities (id, name) VALUES (0, 'Athens');
INSERT INTO cities (id, name) VALUES (1, 'Thessaloniki');
INSERT INTO cities (id, name) VALUES (2, 'Patras');
INSERT INTO cities (id, name) VALUES (3, 'Ioannina');
INSERT INTO cities (id, name) VALUES (4, 'Tirana');
INSERT INTO cities (id, name) VALUES (5, 'Skopje');
INSERT INTO cities (id, name) VALUES (6, 'Sofia');
INSERT INTO cities (id, name) VALUES (7, 'Podgorica');
INSERT INTO cities (id, name) VALUES (8, 'Pristina');
INSERT INTO cities (id, name) VALUES (9, 'Bucharest');
INSERT INTO cities (id, name) VALUES (10, 'Belgrade');
INSERT INTO cities (id, name) VALUES (11, 'Sarajevo');
INSERT INTO cities (id, name) VALUES (12, 'Zagreb');
INSERT INTO cities (id, name) VALUES (13, 'Chisinau');
INSERT INTO cities (id, name) VALUES (14, 'Ljubljana');

CREATE TABLE distances (
    from_city INT NOT NULL,
    to_city INT NOT NULL,
    distance FLOAT NOT NULL,
    PRIMARY KEY (from_city, to_city),
    FOREIGN KEY (from_city) REFERENCES cities(id),
    FOREIGN KEY (to_city) REFERENCES cities(id)
);

INSERT INTO distances (from_city, to_city, distance) VALUES (0, 0, 0);
INSERT INTO distances (from_city, to_city, distance) VALUES (1, 1, 0);
INSERT INTO distances (from_city, to_city, distance) VALUES (2, 2, 0);
INSERT INTO distances (from_city, to_city, distance) VALUES (3, 3, 0);
INSERT INTO distances (from_city, to_city, distance) VALUES (4, 4, 0);
INSERT INTO distances (from_city, to_city, distance) VALUES (5, 5, 0);
INSERT INTO distances (from_city, to_city, distance) VALUES (6, 6, 0);
INSERT INTO distances (from_city, to_city, distance) VALUES (7, 7, 0);
INSERT INTO distances (from_city, to_city, distance) VALUES (8, 8, 0);
INSERT INTO distances (from_city, to_city, distance) VALUES (9, 9, 0);
INSERT INTO distances (from_city, to_city, distance) VALUES (10, 10, 0);
INSERT INTO distances (from_city, to_city, distance) VALUES (11, 11, 0);
INSERT INTO distances (from_city, to_city, distance) VALUES (12, 12, 0);
INSERT INTO distances (from_city, to_city, distance) VALUES (13, 13, 0);
INSERT INTO distances (from_city, to_city, distance) VALUES (14, 14, 0);
INSERT INTO distances (from_city, to_city, distance) VALUES (1, 0, 494);
INSERT INTO distances (from_city, to_city, distance) VALUES (2, 0, 213);
INSERT INTO distances (from_city, to_city, distance) VALUES (3, 0, 412);
INSERT INTO distances (from_city, to_city, distance) VALUES (4, 0, 678);
INSERT INTO distances (from_city, to_city, distance) VALUES (5, 0, 698);
INSERT INTO distances (from_city, to_city, distance) VALUES (6, 0, 798);
INSERT INTO distances (from_city, to_city, distance) VALUES (7, 0, 862);
INSERT INTO distances (from_city, to_city, distance) VALUES (8, 0, 787);
INSERT INTO distances (from_city, to_city, distance) VALUES (9, 0, 1184);
INSERT INTO distances (from_city, to_city, distance) VALUES (10, 0, 1095);
INSERT INTO distances (from_city, to_city, distance) VALUES (11, 0, 1061);
INSERT INTO distances (from_city, to_city, distance) VALUES (12, 0, 1485);
INSERT INTO distances (from_city, to_city, distance) VALUES (13, 0, 1651);
INSERT INTO distances (from_city, to_city, distance) VALUES (14, 0, 1623);
INSERT INTO distances (from_city, to_city, distance) VALUES (2, 1, 468);
INSERT INTO distances (from_city, to_city, distance) VALUES (3, 1, 261);
INSERT INTO distances (from_city, to_city, distance) VALUES (4, 1, 397);
INSERT INTO distances (from_city, to_city, distance) VALUES (5, 1, 234);
INSERT INTO distances (from_city, to_city, distance) VALUES (6, 1, 292);
INSERT INTO distances (from_city, to_city, distance) VALUES (7, 1, 550);
INSERT INTO distances (from_city, to_city, distance) VALUES (8, 1, 323);
INSERT INTO distances (from_city, to_city, distance) VALUES (9, 1, 679);
INSERT INTO distances (from_city, to_city, distance) VALUES (10, 1, 631);
INSERT INTO distances (from_city, to_city, distance) VALUES (11, 1, 820);
INSERT INTO distances (from_city, to_city, distance) VALUES (12, 1, 1023);
INSERT INTO distances (from_city, to_city, distance) VALUES (13, 1, 1140);
INSERT INTO distances (from_city, to_city, distance) VALUES (14, 1, 1162);
INSERT INTO distances (from_city, to_city, distance) VALUES (3, 2, 222);
INSERT INTO distances (from_city, to_city, distance) VALUES (4, 2, 538);
INSERT INTO distances (from_city, to_city, distance) VALUES (5, 2, 622);
INSERT INTO distances (from_city, to_city, distance) VALUES (6, 2, 756);
INSERT INTO distances (from_city, to_city, distance) VALUES (7, 2, 672);
INSERT INTO distances (from_city, to_city, distance) VALUES (8, 2, 744);
INSERT INTO distances (from_city, to_city, distance) VALUES (9, 2, 1143);
INSERT INTO distances (from_city, to_city, distance) VALUES (10, 2, 1057);
INSERT INTO distances (from_city, to_city, distance) VALUES (11, 2, 903);
INSERT INTO distances (from_city, to_city, distance) VALUES (12, 2, 1300);
INSERT INTO distances (from_city, to_city, distance) VALUES (13, 2, 1604);
INSERT INTO distances (from_city, to_city, distance) VALUES (14, 2, 1438);
INSERT INTO distances (from_city, to_city, distance) VALUES (4, 3, 316);
INSERT INTO distances (from_city, to_city, distance) VALUES (5, 3, 415);
INSERT INTO distances (from_city, to_city, distance) VALUES (6, 3, 553);
INSERT INTO distances (from_city, to_city, distance) VALUES (7, 3, 449);
INSERT INTO distances (from_city, to_city, distance) VALUES (8, 3, 504);
INSERT INTO distances (from_city, to_city, distance) VALUES (9, 3, 940);
INSERT INTO distances (from_city, to_city, distance) VALUES (10, 3, 850);
INSERT INTO distances (from_city, to_city, distance) VALUES (11, 3, 680);
INSERT INTO distances (from_city, to_city, distance) VALUES (12, 3, 1164);
INSERT INTO distances (from_city, to_city, distance) VALUES (13, 3, 1407);
INSERT INTO distances (from_city, to_city, distance) VALUES (5, 4, 223);
INSERT INTO distances (from_city, to_city, distance) VALUES (6, 4, 473);
INSERT INTO distances (from_city, to_city, distance) VALUES (7, 4, 158);
INSERT INTO distances (from_city, to_city, distance) VALUES (8, 4, 257);
INSERT INTO distances (from_city, to_city, distance) VALUES (9, 4, 858);
INSERT INTO distances (from_city, to_city, distance) VALUES (10, 4, 603);
INSERT INTO distances (from_city, to_city, distance) VALUES (11, 4, 389);
INSERT INTO distances (from_city, to_city, distance) VALUES (12, 4, 786);
INSERT INTO distances (from_city, to_city, distance) VALUES (13, 4, 1330);
INSERT INTO distances (from_city, to_city, distance) VALUES (14, 4, 924);
INSERT INTO distances (from_city, to_city, distance) VALUES (6, 5, 236);
INSERT INTO distances (from_city, to_city, distance) VALUES (7, 5, 330);
INSERT INTO distances (from_city, to_city, distance) VALUES (8, 5, 91.3);
INSERT INTO distances (from_city, to_city, distance) VALUES (9, 5, 629);
INSERT INTO distances (from_city, to_city, distance) VALUES (10, 5, 432);
INSERT INTO distances (from_city, to_city, distance) VALUES (11, 5, 507);
INSERT INTO distances (from_city, to_city, distance) VALUES (12, 5, 825);
INSERT INTO distances (from_city, to_city, distance) VALUES (13, 5, 1100);
INSERT INTO distances (from_city, to_city, distance) VALUES (14, 5, 963);
INSERT INTO distances (from_city, to_city, distance) VALUES (7, 6, 520);
INSERT INTO distances (from_city, to_city, distance) VALUES (8, 6, 333);
INSERT INTO distances (from_city, to_city, distance) VALUES (9, 6, 383);
INSERT INTO distances (from_city, to_city, distance) VALUES (10, 6, 392);
INSERT INTO distances (from_city, to_city, distance) VALUES (11, 6, 581);
INSERT INTO distances (from_city, to_city, distance) VALUES (12, 6, 785);
INSERT INTO distances (from_city, to_city, distance) VALUES (13, 6, 852);
INSERT INTO distances (from_city, to_city, distance) VALUES (14, 6, 924);
INSERT INTO distances (from_city, to_city, distance) VALUES (8, 7, 254);
INSERT INTO distances (from_city, to_city, distance) VALUES (9, 7, 822);
INSERT INTO distances (from_city, to_city, distance) VALUES (10, 7, 447);
INSERT INTO distances (from_city, to_city, distance) VALUES (11, 7, 230);
INSERT INTO distances (from_city, to_city, distance) VALUES (12, 7, 627);
INSERT INTO distances (from_city, to_city, distance) VALUES (13, 7, 1314);
INSERT INTO distances (from_city, to_city, distance) VALUES (14, 7, 773);
INSERT INTO distances (from_city, to_city, distance) VALUES (9, 8, 721);
INSERT INTO distances (from_city, to_city, distance) VALUES (10, 8, 459);
INSERT INTO distances (from_city, to_city, distance) VALUES (11, 8, 429);
INSERT INTO distances (from_city, to_city, distance) VALUES (12, 8, 883);
INSERT INTO distances (from_city, to_city, distance) VALUES (13, 8, 1193);
INSERT INTO distances (from_city, to_city, distance) VALUES (14, 8, 1024);
INSERT INTO distances (from_city, to_city, distance) VALUES (10, 9, 597);
INSERT INTO distances (from_city, to_city, distance) VALUES (11, 9, 877);
INSERT INTO distances (from_city, to_city, distance) VALUES (12, 9, 990);
INSERT INTO distances (from_city, to_city, distance) VALUES (13, 9, 474);
INSERT INTO distances (from_city, to_city, distance) VALUES (14, 9, 1128);
INSERT INTO distances (from_city, to_city, distance) VALUES (11, 10, 301);
INSERT INTO distances (from_city, to_city, distance) VALUES (12, 10, 396);
INSERT INTO distances (from_city, to_city, distance) VALUES (13, 10, 960);
INSERT INTO distances (from_city, to_city, distance) VALUES (14, 10, 534);
INSERT INTO distances (from_city, to_city, distance) VALUES (12, 11, 402);
INSERT INTO distances (from_city, to_city, distance) VALUES (13, 11, 1249);
INSERT INTO distances (from_city, to_city, distance) VALUES (14, 11, 540);
INSERT INTO distances (from_city, to_city, distance) VALUES (13, 12, 1335);
INSERT INTO distances (from_city, to_city, distance) VALUES (14, 12, 141);
INSERT INTO distances (from_city, to_city, distance) VALUES (14, 13, 1401);

INSERT INTO distances (from_city, to_city, distance) VALUES (14, 3, 1182);
INSERT INTO distances (from_city, to_city, distance) VALUES (0, 1, 494);
INSERT INTO distances (from_city, to_city, distance) VALUES (0, 2, 213);
INSERT INTO distances (from_city, to_city, distance) VALUES (0, 3, 412);
INSERT INTO distances (from_city, to_city, distance) VALUES (0, 4, 678);
INSERT INTO distances (from_city, to_city, distance) VALUES (0, 5, 698);
INSERT INTO distances (from_city, to_city, distance) VALUES (0, 6, 798);
INSERT INTO distances (from_city, to_city, distance) VALUES (0, 7, 862);
INSERT INTO distances (from_city, to_city, distance) VALUES (0, 8, 787);
INSERT INTO distances (from_city, to_city, distance) VALUES (0, 9, 1184);
INSERT INTO distances (from_city, to_city, distance) VALUES (0, 10,1095);
INSERT INTO distances (from_city, to_city, distance) VALUES (0, 11, 1061);
INSERT INTO distances (from_city, to_city, distance) VALUES (0, 12, 1485);
INSERT INTO distances (from_city, to_city, distance) VALUES (0, 13, 1651);
INSERT INTO distances (from_city, to_city, distance) VALUES (0, 14, 1623);

INSERT INTO distances (from_city, to_city, distance) VALUES (1, 2, 468);
INSERT INTO distances (from_city, to_city, distance) VALUES (1, 3, 261);
INSERT INTO distances (from_city, to_city, distance) VALUES (1, 4, 397);
INSERT INTO distances (from_city, to_city, distance) VALUES (1, 5, 234);
INSERT INTO distances (from_city, to_city, distance) VALUES (1, 6, 292);
INSERT INTO distances (from_city, to_city, distance) VALUES (1, 7, 550);
INSERT INTO distances (from_city, to_city, distance) VALUES (1, 8, 323);
INSERT INTO distances (from_city, to_city, distance) VALUES (1, 9, 679);
INSERT INTO distances (from_city, to_city, distance) VALUES (1, 10, 631);
INSERT INTO distances (from_city, to_city, distance) VALUES (1, 11, 820);
INSERT INTO distances (from_city, to_city, distance) VALUES (1, 12, 1023);
INSERT INTO distances (from_city, to_city, distance) VALUES (1, 13, 1140);
INSERT INTO distances (from_city, to_city, distance) VALUES (1, 14, 1162);

INSERT INTO distances (from_city, to_city, distance) VALUES (2, 3, 468);
INSERT INTO distances (from_city, to_city, distance) VALUES (2, 4, 538);
INSERT INTO distances (from_city, to_city, distance) VALUES (2, 5, 622);
INSERT INTO distances (from_city, to_city, distance) VALUES (2, 6, 756);
INSERT INTO distances (from_city, to_city, distance) VALUES (2, 7, 672);
INSERT INTO distances (from_city, to_city, distance) VALUES (2, 8, 744);
INSERT INTO distances (from_city, to_city, distance) VALUES (2, 9, 1143);
INSERT INTO distances (from_city, to_city, distance) VALUES (2, 10, 1057);
INSERT INTO distances (from_city, to_city, distance) VALUES (2, 11, 903);
INSERT INTO distances (from_city, to_city, distance) VALUES (2, 12, 1300);
INSERT INTO distances (from_city, to_city, distance) VALUES (2, 13, 1604);
INSERT INTO distances (from_city, to_city, distance) VALUES (2, 14, 1438);

INSERT INTO distances (from_city, to_city, distance) VALUES (3, 4, 316);
INSERT INTO distances (from_city, to_city, distance) VALUES (3, 5, 415);
INSERT INTO distances (from_city, to_city, distance) VALUES (3, 6, 553);
INSERT INTO distances (from_city, to_city, distance) VALUES (3, 7, 449);
INSERT INTO distances (from_city, to_city, distance) VALUES (3, 8, 504);
INSERT INTO distances (from_city, to_city, distance) VALUES (3, 9, 940);
INSERT INTO distances (from_city, to_city, distance) VALUES (3, 10, 850);
INSERT INTO distances (from_city, to_city, distance) VALUES (3, 11, 680);
INSERT INTO distances (from_city, to_city, distance) VALUES (3, 12, 1164);
INSERT INTO distances (from_city, to_city, distance) VALUES (3, 13, 1407);
INSERT INTO distances (from_city, to_city, distance) VALUES (3, 14, 1182);

INSERT INTO distances (from_city, to_city, distance) VALUES (4, 5, 223);
INSERT INTO distances (from_city, to_city, distance) VALUES (4, 6, 473);
INSERT INTO distances (from_city, to_city, distance) VALUES (4, 7, 158);
INSERT INTO distances (from_city, to_city, distance) VALUES (4, 8, 257);
INSERT INTO distances (from_city, to_city, distance) VALUES (4, 9, 858);
INSERT INTO distances (from_city, to_city, distance) VALUES (4, 10, 603);
INSERT INTO distances (from_city, to_city, distance) VALUES (4, 11, 389);
INSERT INTO distances (from_city, to_city, distance) VALUES (4, 12, 786);
INSERT INTO distances (from_city, to_city, distance) VALUES (4, 13, 1330);
INSERT INTO distances (from_city, to_city, distance) VALUES (4, 14, 924);

INSERT INTO distances (from_city, to_city, distance) VALUES (5, 6, 236);
INSERT INTO distances (from_city, to_city, distance) VALUES (5, 7, 330);
INSERT INTO distances (from_city, to_city, distance) VALUES (5, 8, 91.3);
INSERT INTO distances (from_city, to_city, distance) VALUES (5, 9, 629);
INSERT INTO distances (from_city, to_city, distance) VALUES (5, 10, 432);
INSERT INTO distances (from_city, to_city, distance) VALUES (5, 11, 507);
INSERT INTO distances (from_city, to_city, distance) VALUES (5, 12, 825);
INSERT INTO distances (from_city, to_city, distance) VALUES (5, 13, 1100);
INSERT INTO distances (from_city, to_city, distance) VALUES (5, 14, 963);

INSERT INTO distances (from_city, to_city, distance) VALUES (6, 7, 520);
INSERT INTO distances (from_city, to_city, distance) VALUES (6, 8, 333);
INSERT INTO distances (from_city, to_city, distance) VALUES (6, 9, 383);
INSERT INTO distances (from_city, to_city, distance) VALUES (6, 10, 392);
INSERT INTO distances (from_city, to_city, distance) VALUES (6, 11, 581);
INSERT INTO distances (from_city, to_city, distance) VALUES (6, 12, 785);
INSERT INTO distances (from_city, to_city, distance) VALUES (6, 13, 852);
INSERT INTO distances (from_city, to_city, distance) VALUES (6, 14, 924);

INSERT INTO distances (from_city, to_city, distance) VALUES (7, 8, 254);
INSERT INTO distances (from_city, to_city, distance) VALUES (7, 9, 822);
INSERT INTO distances (from_city, to_city, distance) VALUES (7, 10, 447);
INSERT INTO distances (from_city, to_city, distance) VALUES (7, 11, 230);
INSERT INTO distances (from_city, to_city, distance) VALUES (7, 12, 627);
INSERT INTO distances (from_city, to_city, distance) VALUES (7, 13, 1314);
INSERT INTO distances (from_city, to_city, distance) VALUES (7, 14, 773);

INSERT INTO distances (from_city, to_city, distance) VALUES (8, 9, 721);
INSERT INTO distances (from_city, to_city, distance) VALUES (8, 10, 459);
INSERT INTO distances (from_city, to_city, distance) VALUES (8, 11, 429);
INSERT INTO distances (from_city, to_city, distance) VALUES (8, 12, 883);
INSERT INTO distances (from_city, to_city, distance) VALUES (8, 13, 1193);
INSERT INTO distances (from_city, to_city, distance) VALUES (8, 14, 1024);

INSERT INTO distances (from_city, to_city, distance) VALUES (9, 10, 597);
INSERT INTO distances (from_city, to_city, distance) VALUES (9, 11, 877);
INSERT INTO distances (from_city, to_city, distance) VALUES (9, 12, 990);
INSERT INTO distances (from_city, to_city, distance) VALUES (9, 13, 474);
INSERT INTO distances (from_city, to_city, distance) VALUES (9, 14, 1128);

INSERT INTO distances (from_city, to_city, distance) VALUES (10, 11, 301);
INSERT INTO distances (from_city, to_city, distance) VALUES (10, 12, 396);
INSERT INTO distances (from_city, to_city, distance) VALUES (10, 13, 960);
INSERT INTO distances (from_city, to_city, distance) VALUES (10, 14, 534);

INSERT INTO distances (from_city, to_city, distance) VALUES (11, 12, 402);
INSERT INTO distances (from_city, to_city, distance) VALUES (11, 13, 1249);
INSERT INTO distances (from_city, to_city, distance) VALUES (11, 14, 540);

INSERT INTO distances (from_city, to_city, distance) VALUES (12, 13, 1335);
INSERT INTO distances (from_city, to_city, distance) VALUES (12, 14, 141);

INSERT INTO distances (from_city, to_city, distance) VALUES (13, 14, 1401);
